### ISSUE TITLE
Span element and class use

### ISSUE THREAD

**Issue by reviewer99** [hagecreative/prj-rev-bwfs-dasmoto#2]
Excellent job making use of the span element along with a class to apply the bold, blue color all the prices required! 

https://github.com/hagecreative/prj-rev-bwfs-dasmoto/blob/1ecaaa93fa16fda2f843e715915a964f0651895d/DasmotoArt/index.html#L17

**Comment by hagecreative** [comment]
I see how better formatting makes this read better from your solution.
