### ISSUE TITLE
Alt Attribute

### ISSUE THREAD

**Issue by reviewer99** [hagecreative/prj-rev-bwfs-dasmoto#3]
Nice job making use of the alt attribute on all your images!

There are several benefits to including the attribute for example:
1. It increases the [accessibility](https://www.codecademy.com/articles/accessibility) of your site. 
2. The attribute is used as a backup, in case the image cannot be rendered. 
3.  Optimizes your site for search engine results.

https://github.com/hagecreative/prj-rev-bwfs-dasmoto/blob/1ecaaa93fa16fda2f843e715915a964f0651895d/DasmotoArt/index.html#L15

**Comment by hagecreative** [comment]
Thanks.
