### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by reviewer99** [hagecreative/prj-rev-bwfs-dasmoto#4]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ All stylesheets linked correctly
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ All design specifications met
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ All HTML elements used appropraitly
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ All CSS selectors used correctly
 
### Overall Score: 16/16

Congrats on finishing the Dasmoto project! Overall you did an excellent job making use of all the elements and CSS properties you've learned about so far! Apart from that, you did a great job ensuring your code did not contain any syntax errors. 

The only area I felt your code as a whole could improve on was regarding formatting. To get an idea of the best practices regarding HTML formatting consider reading over this [article](https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html). I also suggest you take a look at this sample [solution](https://gist.github.com/reviewer99/a57d86253eb46b7640c956ece4641130) to compare and contrast how the files are formatted and the whitespace used to separate important sections in the code. As well take a look at the various comments in the code as comments just like having proper formatting help increase the readability of your code which is always a plus.

**Comment by hagecreative** [comment]
Good reminder to look comment and organize my styles and HTML documents.
